# Generated by Django 4.2.1 on 2023-10-03 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_groups_parent_alter_schedule_parent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule',
            new_name='StudentSchedule',
        ),
    ]
