# Generated by Django 4.2.1 on 2023-10-03 10:46

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_schedule_studentschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_desc', ckeditor.fields.RichTextField()),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('groups', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tableitsya', to='home.groups')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ddd', to='home.teacherschedule')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
